# Generated by Django 5.1.7 on 2025-03-24 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates_resume', '0001_initial'),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeMatchScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matching_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='candidates_resume.candidateprofile')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='job_posting.jobposting')),
            ],
            options={
                'ordering': ['-matching_score'],
                'indexes': [models.Index(fields=['job_posting', 'candidate_profile'], name='resume_matc_job_pos_d8a951_idx')],
                'unique_together': {('job_posting', 'candidate_profile')},
            },
        ),
    ]
