# Generated by Django 5.1.7 on 2025-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumematchscore',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
